---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: create-resource
  namespace: tke-chaos-test
spec:
  entrypoint: resource-create
  arguments:
    parameters:
    - name: image
      value: "ccr.ccs.tencentyun.com/tkeimages/tke-chaos:v0.0.1"
    - name: namespace
      value: "tke-chaos-test"
    - name: object-type
      value: "configmaps"
    - name: object-size-bytes
      value: "10000"
    - name: object-count
      value: "0"
    - name: num-clients
      value: "10"
    - name: qps
      value: "10"
    - name: kubeconfig-secret-name
      value: ""
  serviceAccountName: tke-chaos
  workflowTemplateRef:
    name: resource-archestrate
    clusterScope: true
