---
# 功能说明：集群状态采集, 统计集群中Pod和Node的状态
# 参数说明:
#   cluster-status-collect模版参数说明:
#     1. image: 工具镜像, 用于采集集群状态, tke-chaos/cmd/status.go
#     2. kubeconfig-secret-name: 用于指定接入的K8s集群的kubeconfig凭证的secret名称, 如果为空，则默认为当前集群
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cluster-status-collect-template
spec:
  arguments:
    parameters:
    # cluster-status-collect 参数
    - name: image
      value: "ccr.ccs.tencentyun.com/tkeimages/tke-chaos:v0.0.1"
  entrypoint: cluster-status-collect
  templates:
  - name: cluster-status-collect
    inputs:
      parameters:
      - name: image
        description: "工具镜像, 用于采集集群状态"
      - name: kubeconfig-secret-name
        description: "用于指定接入的K8s集群的kubeconfig凭证的secret名称, 如果为空，则默认为当前集群"
    dag:
      tasks:
      - name: internal-cluster-status-collect
        arguments:
          parameters:
          - name: image
            value: "{{inputs.parameters.image}}"
        template: internal-cluster-status-collect
        when: "'{{inputs.parameters.kubeconfig-secret-name}}' == ''"
      - name: external-cluster-status-collect
        arguments:
          parameters:
          - name: image
            value: "{{inputs.parameters.image}}"
          - name: kubeconfig-secret-name
            value: "{{inputs.parameters.kubeconfig-secret-name}}"
        template: external-cluster-status-collect
        when: "'{{inputs.parameters.kubeconfig-secret-name}}' != ''"
    outputs:
      parameters:
      - name: result
        valueFrom:
          expression: "'{{inputs.parameters.kubeconfig-secret-name}}' == '' ? tasks['internal-cluster-status-collect'].outputs.result : tasks['external-cluster-status-collect'].outputs.result"

  - name: internal-cluster-status-collect
    inputs:
      parameters:
      - name: image
        description: "工具镜像, 用于采集集群状态"
    container:
      image: "{{inputs.parameters.image}}"
      command:
      - /kubestress
      - status

  - name: external-cluster-status-collect
    inputs:
      parameters:
      - name: image
        description: "工具镜像, 用于采集集群状态"
      - name: kubeconfig-secret-name
        description: "用于指定接入的K8s集群的kubeconfig凭证的secret名称, 如果为空，则默认为当前集群"
    container:
      image: "{{inputs.parameters.image}}"
      command:
      - /kubestress
      - status
      - --kubeconfig=/.kube/config
      volumeMounts:
      - name: kubeconfig
        mountPath: "/.kube"
        readOnly: true
    volumes:
    - name: kubeconfig
      secret:
        secretName: "{{inputs.parameters.kubeconfig-secret-name}}"
        items:
        - key: config
          path: config
